
sudo: required
language: java

jdk:
  - openjdk8

script:
  - mvn clean compile package assembly:single -DskipTests

before_deploy:
    - mkdir MiningBuild
    - find . -name '*.jar' -exec cp {} ./MiningBuild \;
    - cd /home/travis/build/semantic-conflicts/jackson-core/MiningBuild
    - tar -zcvf result.tar.gz *
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: result.tar.gz
  name: fetchjar-d58d420f116e854bfd7b155cc1aed4e32939e1da
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    all_branches: true 
            